language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
    - packages/nuxt/node_modules
    - packages/gridsome/node_modules
    - packages/recomponents/node_modules
branches:
  only:
    - "master"
# setup image-snapshot tests in the docker
services:
  - docker
notifications:
  email: true
node_js:
  - '12'
install: yarn
jobs:
  include:
    - stage: compile
      name: Build Recomponents and Storybook
      script:
        - yarn workspace @rebilly/recomponents build
        - yarn workspace @rebilly/recomponents build-storybook
    - stage: test
      name: 'Eslint checks and unit tests'
      script:
        - yarn workspace @rebilly/recomponents build-storybook
        - yarn workspace @rebilly/recomponents lint
        - yarn workspace @rebilly/recomponents test
        # run image-snapshot tests in the docker
        # - yarn build-storybook
        # - docker-compose -f ./.image-snapshots/docker-compose.yml up --build
    - stage: deploy
      name: 'Release recomponents to NPM'
      if: branch = master
      script:
        - yarn workspace @rebilly/recomponents build
        - yarn workspace @rebilly/recomponents semantic-release
