language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
    - packages/nuxt/node_modules
    - packages/gridsome/node_modules
    - packages/recomponents/node_modules
branches:
  only:
    - "master"
notifications:
  email: true
node_js:
  - '12'
install: yarn
jobs:
  include:
    - stage: compile
      name: Build Recomponents and Storybook
      before_script:
        - cd packages/recomponents
        - yarn
      script:
        - yarn build
    - stage: test
      name: 'Eslint checks and unit tests'
      before_script:
        - cd packages/recomponents
      script:
        - yarn lint
        - yarn test
    - stage: deploy
      name: 'Release recomponents to NPM and deploy storybook to github pages'
      before_script:
        - cd packages/recomponents
      if: branch = master
      script:
        - yarn build
        - yarn semantic-release
        - yarn build-storybook
        - cd .out
        - git init
        - git config user.name "junyong"
        - git config user.email "junyong.zeng@rebilly.com"
        - git add .
        - git commit -m "Update docs"
        - git push -f "https://${GH_TOKEN}@github.com/Rebilly/rebilly-recomponents.git" master:gh-pages
