version: '3'

services:
  recomponents-docker-tests:
    container_name: recomponents-docker-tests
    build:
      context: ../../../
      dockerfile: ./packages/recomponents/.image-snapshots/Dockerfile
    environment:
      NODE_ENV: development
      PUPPETEER_EXECUTABLE_PATH: google-chrome-unstable
    volumes:
      - ./:/home/pptruser/rebilly/rebilly-recomponents/packages/recomponents/.image-snapshots
      - ../../../docs:/home/pptruser/rebilly/rebilly-recomponents/docs
    command: "yarn run build-image-snapshots"
