name: Node CI
on:
  push:
    branches: [master]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    env:
      NODE_ENV: test
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Init Recomponents
      run: |
        cd packages/recomponents
    - name: Install dependencies 
      run: |
        npm ci
    - name: Build Recomponents
      run: |
        npm run build
    - name: Build Storybook
      run: |
        npm run build
      env:
        CI: true
