name: Check
on:
  push:
    branches: [master]
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    env:
      NODE_ENV: test
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: packages/recomponents
      run: |
        yarn
  compile:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node-version: [10.x]
    env:
      NODE_ENV: test
    steps:
    - name: Build Recomponents
      working-directory: packages/recomponents
      run: |
        yarn build
    - name: Build Storybook
      working-directory: packages/recomponents
      run: |
        yarn build-storybook
  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node-version: [10.x]
    env:
      NODE_ENV: test
    steps:
    - name: Run Linter
      working-directory: packages/recomponents
      run: |
        yarn lint
    - name: Run Tests
      working-directory: packages/recomponents
      run: |
        yarn test